version: '3.8'
services:
  tg-db:
    image: postgres:13
    restart: always
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123556
      POSTGRES_DB: nest
    networks:
      - bronde
  test-db:
    image: postgres:13
    ports:
      - 5430:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123556
      POSTGRES_DB: nest
    networks:
      - bronde
networks:
  bronde:
