prices = [
    {
        "min_spec_count": 1,
        "max_spec_count": 5,
        "month": 60,
        "three_months": 605,
        "three_months_full": 60,
        "six_months": 460,
        "six_months_full": 60,
        "year": 360,
        "year_full": 60,
    },
    # {
    #     "min_spec_count": 1,
    #     "max_spec_count": 5,
    #     "month": 700,
    #     "three_months": 550,
    #     "three_months_full": 1650,
    #     "six_months": 450,
    #     "six_months_full": 2700,
    #     "year": 350,
    #     "year_full": 4200,
    # },
    {
        "min_spec_count": 6,
        "max_spec_count": 10,
        "month": 1000,
        "three_months": 800,
        "three_months_full": 2400,
        "six_months": 650,
        "six_months_full": 3900,
        "year": 500,
        "year_full": 6000,
    },
    {
        "min_spec_count": 11,
        "max_spec_count": 15,
        "month": 1500,
        "three_months": 1150,
        "three_months_full": 3450,
        "six_months": 950,
        "six_months_full": 5700,
        "year": 750,
        "year_full": 9000,
    },
    {
        "min_spec_count": 15,
        "max_spec_count": 30,
        "month": 2500,
        "three_months": 2000,
        "three_months_full": 6000,
        "six_months": 1600,
        "six_months_full": 9600,
        "year": 1250,
        "year_full": 15000,
    },
]
